# Generated by Django 3.2.5 on 2021-07-23 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='energy_saver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True)),
                ('powerMain', models.DecimalField(decimal_places=2, max_digits=5)),
                ('powerSun', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
